### ISSUE TITLE
Error: Bad socket type specified. Valid types are: udp4, udp6

### ISSUE THREAD

**Issue by dncohen** [kkamkou/node-gelf-pro#14]
This package looks like a fit for something I'm trying to do.  But I can't get past the error below.  I'm trying to follow the example configuration from the README.

```
Error: Bad socket type specified. Valid types are: udp4, udp6
    at newHandle (dgram.js:59:9)
    at new Socket (dgram.js:89:16)
    at Object.exports.createSocket (dgram.js:109:10)
    at udp._createSocket (/Users/dave/devel/integration-tools/node_modules/gelf-pro/lib/adapter/udp.js:42:16)
    at udp.send (/Users/dave/devel/integration-tools/node_modules/gelf-pro/lib/adapter/udp.js:66:21)
    at gelf.send (/Users/dave/devel/integration-tools/node_modules/gelf-pro/lib/gelf-pro.js:110:21)
    at /Users/dave/devel/integration-tools/node_modules/gelf-pro/lib/gelf-pro.js:152:14
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

**Comment by dncohen** [comment]
No sooner did I post this, I found my typo.  I'd accidentally put "upd4" instead of "udp4"!
