### ISSUE TITLE
TCP Timeout creates Exceptions

### ISSUE THREAD

**Issue by hewie** [kkamkou/node-gelf-pro#25]
If the timeout has a low value and many logs are generated the node application shuts down with the following exception:

```
 .../gelfTest/node_modules/async/dist/async.js:844
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at .../gelfTest/node_modules/async/dist/async.js:844:36
    at Socket.<anonymous> (.../gelfTest/node_modules/gelf-pro/lib/adapter/tcp.js:37:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Socket.<anonymous> (.../gelfTest/node_modules/gelf-pro/lib/adapter/tcp.js:33:18)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:334:8)
    at tryOnTimeout (timers.js:232:11)
```

This can be recreated with the following code, if the greylog server is running.
```
var log = require('gelf-pro');

log.setConfig({
  adapterName: 'tcp', // optional; currently supported "udp" and "tcp"; default: udp
  adapterOptions: {
    family: 4, // tcp only; optional; version of IP stack; default: 4
    timeout: 100, // tcp only; optional; default: 10000 (10 sec)
    host: '127.0.0.1', // optional; default: 127.0.0.1
    port: 12201, // optional; default: 12201
  },
});

for (var i = 0; i< 1000; i++) {
  log.error("Test");
}

```

**Comment by kkamkou** [comment]
Thank you for the ticket. The TCP adapter was not tested properly, I've cleaned it up and tested with your script. It looks ok now.
