### ISSUE TITLE
UDP: Error handling of long messages causes Exception in async module

### ISSUE THREAD

**Issue by holzig** [kkamkou/node-gelf-pro#29]
Hi,

When the udp adapter logs a message which is bigger than one chunk and an error occurs it still tries to send the other chunks. If another chunk fails you will get the following error:

```
Error: Callback was already called.
    at <...>\node_modules\async\dist\async.js:844:36
    at doSend (dgram.js:368:7)
    at afterDns (dgram.js:358:5)
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
```

This error caused some of your applications to crash.

You can easily reproduce this behavior when you try to send a log message to a non existing / resolvable address (which was the case in our system). See the following test code:

```
const gelf = require('gelf-pro');

gelf.setConfig({
  adapterOptions: {
    host: 'aUnresolvableAddressMaybeBecauseOfATypo.com',
  },
});

// some randomly generated 3000 byte string to get more than one chunk
const randomLongContent = 'zlWP9hmxjtjWmCxblq7Ivl8rz8wXIkScj5gcprlb1iFoadcxUGmKzRBfO7stNaOxypf6LFNjOEUsar8nkR84WMRj4G5kTbqG3PfvtEEOzJbEniRZRIrOi9laZIjHSAtKfbpe9056M6O3uKAEMtFJgKhcIoO8Zh3LI75NS1yOXPX3JrmL1mvcTSWsyn7bDBwBc42cKdYQQebkbhYZo1jRpivy5ADvA8nZG14qBo7vMX9BKRxkMq6vpKWmZAkrQRNDixMQLMlCM4jNnWxRfQZ0FyVbHrUt8zu0Vza9YWEgevUrX1orBKMqu9QDlISOLSEGuCIj8NejGM99FjM52QGN59Dq1lMctMxPIJEqbRs0hevITfEZcQZo8JbeKCj91mXQK0I1IldmXyZM7RGatSxQm1cc8Sx95mblOpSmHtGjmKgwYYJqgDvEU6bRmOhuPGWT0kFN5sP0Joyb5CutBzkmzRlaaBx3w5GuuD5cx0tj89BA1EwGG8FAWoxbJbXdwZmReHi8T1kfTI9ru2J8mEQMktRfawX00PiyBODxCO5QOJphq1bQX1oUNl0eSztHACe8VxuHCgXkDJzjWMNxREgRdftlEmCh4BbZa4h6t44PzV5H07tNXrATjgfX7ce2XvmxnQ4J6kXNqSonQPF06aIEw9OgsHtzLGbYHILENiQIOsdhTePabXKqTewxsccqXejWKf6KPdtJ4EaDNKqvsaYuTVzRfrGml5HxAunBZYxl8gulbapI2SUpcBrsWAL9bs1VNzKKHSqbEBp7B6JmwxOL39Vpx64CfXr0jdmdNQ965DAcYyVcoSnl4yhQ5FRv3HpEvRGsO7LOFadziLSIfsB9TBr83WPaeLFGEGg3dC2m5OeUs2jjnPZIeTuz2AwakhObyqQFsqaGDmPscl7kNiMBJH0AXilCKlIKjrPyDXDBhQHqQHgqu9qIkdX47iSo8LOP2yY4yyqDhyJXC1OMCXH6C2FPaVtPaq4VuISghv7MIWTitk52g21aMsYziVxzFv6ryjRJfcld9096U6xKpMbGwWrgsCsH2XUpFWHhTSdWQByGs33nkhqTmIxnB2geRL32n3ycDbxqdEZHajSOZZ7SRVNuNiS3619B8txGrQGwfqsG8yy8m9hp8bmKAHLnFnHiZwuK1FxDARNXA8L4WbvAwFVwWFMbfOCvnXlNx5amr1APDj0t3DxF5UzBCJYNQ48S56ljT3dSDJDoBvHROfR9cPKzcdWFSnJ2d8vCoBTMJeE3W8cil93Rfr993ywKEhnOzo32qlFD3RuTJHVSXkMow5J7jwePejUA3SdGuf380PzGq4rtpYx7PqZgFlbENbvEhUud9cqcaG80aVV2iWSuqjhjezGaaEoZoWFsTH9n7oK4X4sI5lHmRhYE94CpU8rROOCUJHWnFraFNqwi0GaiHI4yoOYEZyKiU1JjF5Bfr6OFUpckg3lhne33Y4N5SoUgO0HrLRJg8fOvDajwi5zUnIaKWSEHQH8pzOcvdLSNgyO56EJeFcRLLseCvFKl5RjFGCXKkxPbTRkNx6IwpUNiy5rZZyy8MW1whQHYkOBcyKeynxfRoBLiRmnHIoDk9EM05Es37FBCzfQhF8oCNS46oYjPAh3stFyW1vLXVOM5zFs1l3vuRMz4wDNPEGoJsUpQRGVbpHR6SLf5mYhaJ7oH3bn12802wj9xB7q5hHDduqBYWg9zDW5kk9wyxfqxMFWwTmjGZvG3z12GyK0lrX3tx3xCrm5GvDBlL5cL89aylhUGAIXSNketvykVoGdTa74SRpvIeVLtfo4wQHYGXMYv4ONMnvbzUAR3u5Gzc1n0HjDQUOfIjafvScKSVaVffAGixjj8vjnJE71tlA5zAhuVB7Sb9EeltUOWtnsgUEMB2gu32VzEFvZgYBWAJAOuOMHoAs1zeZ9fInWJa4VLHmdTXc1pWYAam68EaTkzHdN39VVjr7eRmxripKVnUtYRHc2WXgcByc0YuV1U2PfMPKESbw0PdiBd1QHeqeT8EHXlA0i3SGYfRsQAFUEbw58vjBleJwjwxHd5rXfeAvI4dDqCacKTmJGkgRnGW9OCSuYtDkRFqyR0ZO8Y7Vth71nUWwd3B1cgoLmOGe0zAHczRV3OToJEefZEyZC25Ye3VgSPUN1lUzp0KxPeslcCCFeotEavw4AAwvRk6BZ7xIepxsJIzzy9EV6Sxk8piBxPgHlapPQREs172Wg1upFEOpllSitKXG1FaS3SELwmLvNlSZg6SWpXLdQyAd0jeB1WmbGLnWYeGIKuob1Ba9C7LA9Tmh3qYNo6UU8DvT5cGB4hXhTaVLB0Bwqg0IqvNhSvEQQb6vO0IvpYR8bGu8PYrAwdBntIrWuax9OsV8kQd6f8W3CrlCc91BbJNW7U7E6TIgHl4hr3ZLhRFT5btgUllDr5dTykWqxJtSphMrP0xMBNyCKkBpuRlj5IdKvxQWizkq3NTpeHORozV3tjhAC88srExPEdz1RLXa4VGIZY7vOy3D5abwJ4UrF6D1XRizZOMQmYdFknt7vScDeN8hdME8qdUpLLSx5FRgnOnKZiVJtyWFfqaZjXrqnkxYVBUomglIk8URXcBgPZmR82SKuSvJwzpi40llOmJnjetKSmhTTxdfjOOxfkWMdTk8Xt4fQnPoL0X1KjEk63oLud4paCIau3CmiQBqC3t6StVhlwH3TYAy3izGJceUqv7AE03KemEvBxiWIVoHt7l4bkw4mcYxGc9frZLx4xaHo46DeJt2sAPPcLPtN3xrlvcdyaUYeQNhDgXF8Zwlan4LesPNSjYJMG2Ar3EMXbMS8roZs4nVbH2g5MtydHCXGEAaii2JBEG0VflqT8Jbg6c9mcLBPo1XcDHaSAh63pntt9wLeT71yt4ZTWLe4I8vqTS1QPWODnFYowKAktSJNv3MTndcxDuoQI0NpbU4gkzk7ofjPjkN30GD2GZVRL1j66Kf6v40AYWyL3oKfnkKRbe2baI3yY';

gelf.debug(randomLongContent, (err, bytesSent) => {
  console.log({ err, bytesSent });
});
```

**Comment by kkamkou** [comment]
Thank you for the report and the code piece. Very good quality of the ticket. I've bumped a new patch version `1.1.1`. Please reopen the ticket if the problem does exist.

**Comment by holzig** [comment]
Thanks! I will try it soon.

Out of curiosity: What happened to Version 1.2.0?

**Comment by kkamkou** [comment]
The current [change set](https://github.com/kkamkou/node-gelf-pro/compare/1.1.0...1.1.1) has only polishing stuff plus this issue (which is a good catch). `1.2.x` requires some minor design corrections. I've reverted (e5f4e79549dd6f36f65dcbad306bfb66b854e36e) the `package.json` file in case you aren't using npm.
