### ISSUE TITLE
TCP adapter it doesn't work properly 

### ISSUE THREAD

**Issue by beinnova** [kkamkou/node-gelf-pro#35]
Hi,
I'm trying to use the module with the TCP adapter but seems it doesn't work properly. Every message sent to the graylog server it's has the level set as  -1, the `short_message` as the whole extra field.

I use the `.message` function passing message, level extra and a callback function. I tried to use the al other level function like `info` `warn` but nothing changes. I also tried to use a `transform` function and set those parameters as the extra parameter (extra is a JSON in my case) but nothing change.

Let me know if you need some other info from me.

**Comment by kkamkou** [comment]
Please paste the way you call `message()`. Whereas `message()`  is the low-level function for deep integration with 3rd parties, you might want to use: `.info('hello', {world: 555})`. `.error('test', {payload: 'bbb'})` and so on.

`message()` function example is: `.message('hello', 7, {world: 555})`. Where `7` is link [to this one](https://github.com/kkamkou/node-gelf-pro/blob/master/lib/gelf-pro.js#L30:L39).

**Comment by beinnova** [comment]
```javascript
	Gelf.setConfig({
		fields: {facility: 'log-service-tcp', owner: 'Josh'}, // optional; default fields for all messages
		transform: [
			function(message) {
				message.short_message = message.message;
				message.facility = message.service || 'no service';
				message.level = message.type;

				return message;

			}
		],
		adapterName: 'tcp', // optional; currently supported "udp", "tcp" and "tcp-tls"; default: udp
		adapterOptions: { // this object is passed to the adapter.connect() method
		        //common
			host:configs.host, // optional; default: 127.0.0.1
			port: configs.port, // optional; default: 12201
			// tcp adapter example
			family: 4, // tcp only; optional; version of IP stack; default: 4
			timeout: 1000, // tcp only; optional; default: 10000 (10 sec)
		}
	});

	this._priv.graylog = Gelf;


			this._priv.graylog.message(message.message, 7, message,  function(err, bytesSent) {
				console.log(bytesSent);
				callback && callback(err);
			});
```

```javascript
full_message

{"version":"1.1","short_message":"An error occurred while attempting to stop a monitor manager.","timestamp":1509116478.396,"host":"ncc-1701-c","level":"warn","_facility":"template service","_owner":"Josh","_message":"An error occurred while attempting to stop a monitor manager.","_configs":"[object Object]","_error_errorId":160205,"_error_internalStack":"    at FS.stop (/application/node_modules/cam-resource-monitor/lib/monitor/manager/plugins/fs.js:168:25),    at Manager.stop (/application/node_modules/cam-resource-monitor/lib/monitor/manager/index.js:156:21),    at Monitor.<anonymous> (/application/node_modules/cam-resource-monitor/lib/monitor/index.js:145:33),    at Object.async.whilst (/application/node_modules/async/lib/async.js:792:13),    at Monitor.stop (/application/node_modules/cam-resource-monitor/lib/monitor/index.js:137:9),    at Monitor.<anonymous> (/application/node_modules/cam-resource-monitor/lib/monitor/index.js:96:10),    at /application/node_modules/async/lib/async.js:52:16,    at /application/node_modules/async/lib/async.js:361:13,    at /application/node_modules/async/lib/async.js:52:16","_error_instance":1509099436003,"_error_retry":"false","_hostname":"camlinux4","_file":"/application/node_modules/cam-resource-monitor/lib/monitor/index.js","_service":"template service","_date":"2017-10-27T10:17:16.007Z","_type":"warn","_subType":""}
level

-1
message

{"version":"1.1","short_message":"An error occurred while attempting to stop a monitor manager.","timestamp":1509116478.396,"host":"ncc-1701-c","level":"warn","_facility":"template service","_owner":"Josh","_message":"An error occurred while attempting to stop a monitor manager.","_configs":"[object Object]","_error_errorId":160205,"_error_internalStack":"    at FS.stop (/application/node_modules/cam-resource-monitor/lib/monitor/manager/plugins/fs.js:168:25),    at Manager.stop (/application/node_modules/cam-resource-monitor/lib/monitor/manager/index.js:156:21),    at Monitor.<anonymous> (/application/node_modules/cam-resource-monitor/lib/monitor/index.js:145:33),    at Object.async.whilst (/application/node_modules/async/lib/async.js:792:13),    at Monitor.stop (/application/node_modules/cam-resource-monitor/lib/monitor/index.js:137:9),    at Monitor.<anonymous> (/application/node_modules/cam-resource-monitor/lib/monitor/index.js:96:10),    at /application/node_modules/async/lib/async.js:52:16,    at /application/node_modules/async/lib/async.js:361:13,    at /application/node_modules/async/lib/async.js:52:16","_error_instance":1509099436003,"_error_retry":"false","_hostname":"camlinux4","_file":"/application/node_modules/cam-resource-monitor/lib/monitor/index.js","_service":"template service","_date":"2017-10-27T10:17:16.007Z","_type":"warn","_subType":""}
source

194.143.183.65
timestamp

2017-10-27T15:01:22.733Z

```

I've tried with other function like `.info()` or `.warn()` but the result as the same. Actually, I would like to send a raw object is is it possible.

**Comment by kkamkou** [comment]
@beinnova Could you create a screenshot of the graylog input settings and post the raw message you're trying to send?

**Comment by beinnova** [comment]
@kkamkou 
```javascript
{ "message" : "An error occurred while attempting to stop a monitor manager.", "configs" : [ { "env" : "resource-monitor", "globals" : "resource-monitor", "resourceExpires" : 60000, "thumbnailExpires" : 60000, "createThumbnailDelay" : 500, "resourceGlob" : "+(xar|web|jpg|jpeg|png)", "thumbnailGlob" : "+(jpg|jpeg|png)", "directoryThumbnailName" : "folder-image.png", "mongo" : { "host" : "127.0.0.1", "port" : 27017, "database" : "Resources", "collection" : "folders" }, "type" : "fs", "identifier" : "templates", "filter" : {  }, "root" : "/application_templates/DevTemplates", "scanMaxDepth" : 10, "thumbnailsFolderName" : "xarainfo", "thumbnailURL" : "http://camlinux4.ixara.com/images/thumbnail/{0}" } ], "error" : { "errorId" : 160205, "internalStack" : [ "    at FS.stop (/application/node_modules/cam-resource-monitor/lib/monitor/manager/plugins/fs.js:168:25)", "    at Manager.stop (/application/node_modules/cam-resource-monitor/lib/monitor/manager/index.js:156:21)", "    at Monitor.<anonymous> (/application/node_modules/cam-resource-monitor/lib/monitor/index.js:145:33)", "    at Object.async.whilst (/application/node_modules/async/lib/async.js:792:13)", "    at Monitor.stop (/application/node_modules/cam-resource-monitor/lib/monitor/index.js:137:9)", "    at Monitor.<anonymous> (/application/node_modules/cam-resource-monitor/lib/monitor/index.js:96:10)", "    at /application/node_modules/async/lib/async.js:52:16", "    at /application/node_modules/async/lib/async.js:361:13", "    at /application/node_modules/async/lib/async.js:52:16" ], "instance" : 1509099436003, "retry" : false }, "hostname" : "camlinux4", "file" : "/application/node_modules/cam-resource-monitor/lib/monitor/index.js", "service" : "template service", "date" : "2017-10-27T10:17:16.007Z", "type" : "warn", "subType" : null } 
```

![schermata del 2017-10-30 09-59-27](https://user-images.githubusercontent.com/2893182/32162539-ac675fb4-bd59-11e7-806e-858b47a06813.png)
![schermata del 2017-10-30 10-00-31](https://user-images.githubusercontent.com/2893182/32162553-b2041340-bd59-11e7-9bf5-bbf67180dbcb.png)

**Comment by kkamkou** [comment]
Are you sure that the input is `GELF TCP`? It looks like this one is Syslog.

**Comment by beinnova** [comment]
@kkamkou you are right! Thank you for the help that you gave me and many compliments for your grate job.

**Comment by kkamkou** [comment]
thx for the feedback, you're welcome.
